### ISSUE TITLE
Add a log view to the job status page in the user interface

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-web#52]
From this comment:
https://github.com/Electrostatics/pdb2pqr/issues/214#issuecomment-894923612_

Build a log view for PDB2PQR and APBS to display the .log, .stdout, and .stderr contents.  This would allow users to easily view the output of a successful/failed run.

### Tasks:
- [x] Add collapsible log view for <job_id>.log file
- [x] Add collapsible log view for <job_id>.stdout file
- [x] Add collapsible log view for <job_id>.stderr file
